package io.scmspain.tech2014.repo;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ItemsRepo {

    private static Map<String, List<String>> map = new HashMap<String, List<String>>();

    static{
        List<String> ls1 = new ArrayList<String>();
        List<String> ls2 = new ArrayList<String>();
        List<String> ls3 = new ArrayList<String>();
        List<String> ls4 = new ArrayList<String>();
        List<String> ls5 = new ArrayList<String>();
//        List<String> ls6 = new ArrayList<String>();
//        List<String> ls7 = new ArrayList<String>();

        ls1.add("Terelu Campos");
        ls1.add("Curro Romero");
        ls1.add("Carmen Tello");
        ls1.add("Alfonso Díez");
        ls1.add("Jesus Aguirre");

        ls2.add("Pantoja");
        ls2.add("Carmen Ordoñez");
        ls2.add("Dani Mateo");
        ls2.add("Belen Esteban");
        ls2.add("Mercedes Milá");
        ls2.add("Raquel Bollo");

        ls3.add("Javier Camara");
        ls3.add("Tony Leblanc");
        ls3.add("Poli Diaz");
        ls3.add("El Gran wyoming");
        ls3.add("Carlitos");
        ls3.add("Luis Cuenca");

        ls4.add("Abomasnow");
        ls4.add("Abra");
        ls4.add("Absol");
        ls4.add("Accelgor");
        ls4.add("Aegislash");
        ls4.add("Aerodactyl");
        ls4.add("Aggron");
        ls4.add("Aipom");
        ls4.add("Alakazam");
        ls4.add("Alomomola");
        ls4.add("Altaria");
        ls4.add("Amaura");
        ls4.add("Ambipom");
        ls4.add("Amoonguss");
        ls4.add("Ampharos");
        ls4.add("Anorith");
        ls4.add("Arbok");
        ls4.add("Arcanine");
        ls4.add("Arceus");
        ls4.add("Archen");
        ls4.add("Archeops");
        ls4.add("Ariados");
        ls4.add("Armaldo");
        ls4.add("Aromatisse");
        ls4.add("Aron");
        ls4.add("Articuno");
        ls4.add("Audino");
        ls4.add("Aurorus");
        ls4.add("Avalugg");
        ls4.add("Axew");
        ls4.add("Azelf");
        ls4.add("Azumarill");
        ls4.add("Azurill");
        ls4.add("Bagon");
        ls4.add("Baltoy");
        ls4.add("Banette");
        ls4.add("Barbaracle");
        ls4.add("Barboach");
        ls4.add("Basculin");
        ls4.add("Bastiodon");
        ls4.add("Bayleef");
        ls4.add("Beartic");
        ls4.add("Beautifly");
        ls4.add("Beedrill");
        ls4.add("Beheeyem");
        ls4.add("Beldum");
        ls4.add("Bellossom");
        ls4.add("Bellsprout");
        ls4.add("Bergmite");
        ls4.add("Bibarel");
        ls4.add("Bidoof");
        ls4.add("Binacle");
        ls4.add("Bisharp");
        ls4.add("Blastoise");
        ls4.add("Blaziken");
        ls4.add("Blissey");
        ls4.add("Blitzle");
        ls4.add("Boldore");
        ls4.add("Bonsly");
        ls4.add("Bouffalant");
        ls4.add("Braixen");
        ls4.add("Braviary");
        ls4.add("Breloom");
        ls4.add("Bronzong");
        ls4.add("Bronzor");
        ls4.add("Budew");
        ls4.add("Buizel");
        ls4.add("Bulbasaur");
        ls4.add("Buneary");
        ls4.add("Bunnelby");
        ls4.add("Burmy");
        ls4.add("Butterfree");
        ls4.add("Cacnea");
        ls4.add("Cacturne");
        ls4.add("Camerupt");
        ls4.add("Carbink");
        ls4.add("Carnivine");
        ls4.add("Carracosta");
        ls4.add("Carvanha");
        ls4.add("Cascoon");
        ls4.add("Castform");
        ls4.add("Caterpie");
        ls4.add("Celebi");
        ls4.add("Chandelure");
        ls4.add("Chansey");
        ls4.add("Charizard");
        ls4.add("Charmander");
        ls4.add("Charmeleon");
        ls4.add("Chatot");
        ls4.add("Cherrim");
        ls4.add("Cherubi");
        ls4.add("Chesnaught");
        ls4.add("Chespin");
        ls4.add("Chikorita");
        ls4.add("Chimchar");
        ls4.add("Chimecho");
        ls4.add("Chinchou");
        ls4.add("Chingling");
        ls4.add("Cinccino");
        ls4.add("Clamperl");
        ls4.add("Clauncher");
        ls4.add("Clawitzer");
        ls4.add("Claydol");
        ls4.add("Clefable");
        ls4.add("Clefairy");
        ls4.add("Cleffa");
        ls4.add("Cloyster");
        ls4.add("Cobalion");
        ls4.add("Cofagrigus");
        ls4.add("Combee");
        ls4.add("Combusken");
        ls4.add("Conkeldurr");
        ls4.add("Corphish");
        ls4.add("Corsola");
        ls4.add("Cottonee");
        ls4.add("Cradily");
        ls4.add("Cranidos");
        ls4.add("Crawdaunt");
        ls4.add("Cresselia");
        ls4.add("Croagunk");
        ls4.add("Crobat");
        ls4.add("Croconaw");
        ls4.add("Crustle");
        ls4.add("Cryogonal");
        ls4.add("Cubchoo");
        ls4.add("Cubone");
        ls4.add("Cyndaquil");
        ls4.add("Darkrai");
        ls4.add("Darmanitan");
        ls4.add("Darumaka");
        ls4.add("Dedenne");
        ls4.add("Deerling");
        ls4.add("Deino");
        ls4.add("Delcatty");
        ls4.add("Delibird");
        ls4.add("Delphox");
        ls4.add("Deoxys");
        ls4.add("Dewgong");
        ls4.add("Dewott");
        ls4.add("Dialga");
        ls4.add("Diancie");
        ls4.add("Diggersby");
        ls4.add("Diglett");
        ls4.add("Ditto");
        ls4.add("Dodrio");
        ls4.add("Doduo");
        ls4.add("Donphan");
        ls4.add("Doublade");
        ls4.add("Dragalge");
        ls4.add("Dragonair");
        ls4.add("Dragonite");
        ls4.add("Drapion");
        ls4.add("Dratini");
        ls4.add("Drifblim");
        ls4.add("Drifloon");
        ls4.add("Drilbur");
        ls4.add("Drowzee");
        ls4.add("Druddigon");
        ls4.add("Ducklett");
        ls4.add("Dugtrio");
        ls4.add("Dunsparce");
        ls4.add("Duosion");
        ls4.add("Durant");
        ls4.add("Dusclops");
        ls4.add("Dusknoir");
        ls4.add("Duskull");
        ls4.add("Dustox");
        ls4.add("Dwebble");
        ls4.add("Eelektrik");
        ls4.add("Eelektross");
        ls4.add("Eevee");
        ls4.add("Ekans");
        ls4.add("Electabuzz");
        ls4.add("Electivire");
        ls4.add("Electrike");
        ls4.add("Electrode");
        ls4.add("Elekid");
        ls4.add("Elgyem");
        ls4.add("Emboar");
        ls4.add("Emolga");
        ls4.add("Empoleon");
        ls4.add("Entei");
        ls4.add("Escavalier");
        ls4.add("Espeon");
        ls4.add("Espurr");
        ls4.add("Excadrill");
        ls4.add("Exeggcute");
        ls4.add("Exeggutor");
        ls4.add("Exploud");
        ls4.add("Farfetch'd");
        ls4.add("Fearow");
        ls4.add("Feebas");
        ls4.add("Fennekin");
        ls4.add("Feraligatr");
        ls4.add("Ferroseed");
        ls4.add("Ferrothorn");
        ls4.add("Finneon");
        ls4.add("Flaaffy");
        ls4.add("Flabébé");
        ls4.add("Flareon");

        ls5.add("Han Solo");
        ls5.add("Princesa Leia");
        ls5.add("Chewbacca");
        ls5.add("C-3PO");
        ls5.add("R2-D2");
        ls5.add("Yoda");
        ls5.add("Darth Vader");
        ls5.add("Boba Fett");
        ls5.add("Luke Skywalker");

        map = new HashMap();
        map.put("Cayetana", ls1);
        map.put("Paquirrin", ls2);
        map.put("Torrente",ls3);
        map.put("Chuck norris", ls4);
        map.put("Obi-Wan Kenobi", ls5);
        map.put("Pocholo", null);


    };


    public static List<String> getFriendsFor(String name){
        return map.get(name);
    }
}
